name: Build and Publish Release

on:
 push:
   tags:
     - 'releases/*'
     - '!releases/**-beta'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm install
      - run: npm test
        env:
          CI: true
      - run: npm run browser
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://registry.npmjs.org/
      - run: npm config set package-lock false
      - run: npm install
      - run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@meeco"
          npm publish --access public 
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}